export const GET_USER = 'GET_USER';
export const ADD_RECORD = 'ADD_RECORD';
export const ADD_RECORD_ERROR = 'ADD_RECORD_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';